In [30]:
import pandas as pd
import numpy as np

In [31]:
#loading dataset
cars_data=pd.read_csv(r'D:\Others\Downloads\\cars.csv',header=None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [32]:
cars_data.shape     #gives the no of (rows,columns) in the dataset

(1728, 7)

In [33]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']  #changing the column names in the data
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [34]:
cars_data.classes.value_counts()       

unacc    1210
acc       384
good       69
vgood      65
Name: classes, dtype: int64

In [35]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [36]:
cars_df=pd.DataFrame.copy(cars_data)      #creating a copy of the file

In [37]:
colname=cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [38]:
from sklearn import preprocessing

le={}

for x in colname:
    le[x]=preprocessing.LabelEncoder()
    
for x in colname:
    cars_df[x]=le[x].fit_transform(cars_df[x])

In [39]:
X=cars_df.values[:,:-1]
Y=cars_df.values[:,-1]

In [40]:
from sklearn.preprocessing import StandardScaler
#use "fit" only on training data and not on testing data
#"transform" should be applied to both training and testing data

scaler=StandardScaler()

scaler.fit(X)
X = scaler.transform(X)

C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [41]:
from sklearn.model_selection import train_test_split

#split the data into train and test

X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.3,random_state=10)

# Running Decision Tree Model

In [42]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10)

model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [43]:
print(list(zip(colname,model_DecisionTree.feature_importances_)))

[('buying', 0.1510848831946676), ('maint', 0.2506508516803624), ('doors', 0.060026331736828115), ('persons', 0.19355707150872045), ('lug_boot', 0.09892620952419463), ('safety', 0.2457546523552268)]


In [44]:
Y_pred=model_DecisionTree.predict(X_test)
print(Y_pred)

[2 2 2 2 1 2 0 0 2 0 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2
 2 2 0 2 2 2 3 2 0 2 2 2 2 2 0 1 3 1 2 0 2 0 2 2 2 2 3 2 2 0 0 2 2 3 2 2 2
 1 2 0 0 2 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2
 2 2 2 0 2 2 1 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 3 2 2 0 2 0 3 2 2 2 2
 2 2 2 2 3 2 2 2 2 2 1 1 2 0 2 2 2 2 2 2 2 2 2 1 2 3 2 2 2 2 0 0 2 2 2 2 3
 2 0 2 1 0 2 2 2 2 0 3 0 0 2 2 2 2 0 2 2 2 2 2 2 2 3 0 2 2 2 3 2 2 1 2 2 2
 2 2 2 2 0 2 2 2 2 2 0 0 2 2 2 2 3 2 2 0 2 0 2 0 2 2 2 2 2 0 2 2 2 0 2 2 0
 2 2 2 0 2 2 2 0 2 2 0 2 2 2 1 1 2 2 2 0 2 2 0 3 3 0 2 0 2 2 2 3 2 2 0 2 2
 2 2 2 0 2 2 2 3 2 2 2 0 2 2 2 2 0 0 2 2 1 2 2 2 0 2 2 0 0 2 0 0 2 2 0 0 2
 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 1 3 3 2 2 2 2 0 2 2 2 3 2 2 0 2 1 2 2 2
 0 0 2 2 2 2 2 2 2 0 2 0 1 2 2 2 2 2 0 2 2 3 0 0 0 0 2 0 2 2 2 0 0 2 0 2 1
 0 2 2 0 2 2 2 0 1 2 0 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 3 2 2 2 2 0 2 2
 2 0 2 2 2 0 2 2 2 0 2 2 0 3 2 2 2 2 0 2 2 2 2 2 2 0 2 0 2 0 2 2 2 2 0 2 2
 2 2 2 2 2 2 2 1 2 2 2 2 

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[101   0   1   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9922928709055877
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.99      0.96      0.98       519
weighted avg       0.99      0.99      0.99       519



In [46]:
from sklearn import tree
with open(r'D:\Others\Downloads\carsmodel_DecisionTree.txt', "w") as f:
    f = tree.export_graphviz(model_DecisionTree, 
                        feature_names=cars_df.columns[:-1],out_file=f)

#generate the file and upload the code in webgraphviz.com to plot the decision tree



In [47]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=(LogisticRegression())
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 22   0  80   0]
 [  3   0  18   0]
 [ 30   0 341   0]
 [ 11   0  14   0]]
0.6994219653179191
              precision    recall  f1-score   support

           0       0.33      0.22      0.26       102
           1       0.00      0.00      0.00        21
           2       0.75      0.92      0.83       371
           3       0.00      0.00      0.00        25

   micro avg       0.70      0.70      0.70       519
   macro avg       0.27      0.28      0.27       519
weighted avg       0.60      0.70      0.64       519



C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [49]:
#SVM Classifier
from sklearn.svm import SVC

svc_model=SVC(kernel="rbf", C=1,gamma=0.1)
svc_model.fit(X_train, Y_train)
Y_pred=svc_model.predict(X_test)

print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))



[[ 82   0  20   0]
 [ 21   0   0   0]
 [ 17   0 354   0]
 [ 17   0   0   8]]
0.8554913294797688
              precision    recall  f1-score   support

           0       0.60      0.80      0.69       102
           1       0.00      0.00      0.00        21
           2       0.95      0.95      0.95       371
           3       1.00      0.32      0.48        25

   micro avg       0.86      0.86      0.86       519
   macro avg       0.64      0.52      0.53       519
weighted avg       0.84      0.86      0.84       519



C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [51]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier       

model=(ExtraTreesClassifier(21))             #creates 21 bags of samples/ implements 21 decision trees (default is 10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 95   4   3   0]
 [  4  16   0   1]
 [  1   0 370   0]
 [  6   0   0  19]]
0.9633911368015414
              precision    recall  f1-score   support

           0       0.90      0.93      0.91       102
           1       0.80      0.76      0.78        21
           2       0.99      1.00      0.99       371
           3       0.95      0.76      0.84        25

   micro avg       0.96      0.96      0.96       519
   macro avg       0.91      0.86      0.88       519
weighted avg       0.96      0.96      0.96       519



In [80]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import RandomForestClassifier       

model=(RandomForestClassifier(70))             #creates 21 bags of samples/ implements 21 decision trees (default is 10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 98   3   0   1]
 [  2  18   0   1]
 [  2   0 369   0]
 [  1   0   0  24]]
0.9807321772639692
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       102
           1       0.86      0.86      0.86        21
           2       1.00      0.99      1.00       371
           3       0.92      0.96      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.93      0.94      0.94       519
weighted avg       0.98      0.98      0.98       519



In [86]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import AdaBoostClassifier       

model=AdaBoostClassifier(base_estimator=DecisionTreeClassifier())             #creates 10 bags of samples/ implements 21 decision trees (default is 10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[100   1   1   0]
 [  3  18   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9884393063583815
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       102
           1       0.95      0.86      0.90        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.98      0.95      0.96       519
weighted avg       0.99      0.99      0.99       519



In [89]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import GradientBoostingClassifier       

model=GradientBoostingClassifier()             #creates 10 bags of samples/ implements 21 decision trees (default is 10)
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[100   2   0   0]
 [  0  19   0   2]
 [  0   0 371   0]
 [  0   0   0  25]]
0.9922928709055877
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       102
           1       0.90      0.90      0.90        21
           2       1.00      1.00      1.00       371
           3       0.93      1.00      0.96        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.96      0.97      0.96       519
weighted avg       0.99      0.99      0.99       519



In [91]:
#importing packages

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

 

# create the sub models
estimators = []
model1 = LogisticRegression()
estimators.append(('log', model1))
model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))
model3 = SVC()
estimators.append(('svm', model3))

# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)



C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [92]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 89   0  13   0]
 [ 19   2   0   0]
 [  4   0 367   0]
 [  5   0   0  20]]
0.9210019267822736
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       102
           1       1.00      0.10      0.17        21
           2       0.97      0.99      0.98       371
           3       1.00      0.80      0.89        25

   micro avg       0.92      0.92      0.92       519
   macro avg       0.93      0.69      0.71       519
weighted avg       0.93      0.92      0.91       519

