In [2]:
import numpy as np
np.__version__


'1.15.4'

In [3]:
a=np.array([1,2,3])        #creates 1D array
print(a)
print(type(a))            #returns the data type. here, n dimensional array

[1 2 3]


In [25]:
a=np.array([[1,2,3],[4,5,6]])        #creates 2x3 array
print(a)
print(type(a))
print(a.ndim)                        #ndim is for dimension number i.e. 2
print(a.shape)                              #shape is for no. of rows & columns

a=np.array([[1,2,3,4],[4,5,6]])        #creates 1x2 matrix
print(a)
print(a.ndim)            

a,b=np.ones((2,3,4))                #creates 2 arrays of 3 rosws and 4 columns
print(a)
print(b)            

a,b=np.zeros((2,3,4),dtype=np.int)  #creates 2 arrays of 3 rows and 4 columns
print(a)
print()                            #prints blank space
print(b)            

a,b=np.full((2,5,5),2.5)                #creates 2 arrays of 2 rows and 2 columns with element 3
print(a)
print(b)            

a=np.identity(3, dtype=np.int)                #creates 2 arrays of 2 rows and 2 columns with element 
print(a)

a=np.random.random((5,2))
print(a)

a=np.random.random_integers(50,100,(3,4))
print(a)

a=np.array([(1,2,3,4),(4,5,6,7)])                #creates 2 arrays of 2 rows and 2 columns with element 3
print(a)
print(a.size)            
print(a.shape)          

a=np.resize(a,(6,3))                        #resizes the array into 6x3
a=np.reshape(a,(2,9))                       #the no. of rows and columns should match with the no. of elements
print(a)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
[list([1, 2, 3, 4]) list([4, 5, 6])]
1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]]
[[2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5 2.5]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.86778583 0.14542159]
 [0.26240498 0.50632837]
 [0.0145875  0.73159148]
 [0.316974   0.49459092]
 [0.80105479 0.08433927]]
[[ 61  83  57  65]
 [ 91 100  80  69]
 [ 68  71  76  62]]
[[1 2 3 4]
 [4 5 6 7]]
8
(2, 4)
[[1 2 3 4 4 5 6 7 1]
 [2 3 4 4 5 6 7 1 2]]


C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: DeprecationWarning: This function is deprecated. Please call randint(50, 100 + 1) instead


In [27]:
#indexing & slicing
a=np.array([(1,2,3,4),(3,4,5,6),(8,9,10,11)]) 
print(a)
print(a[0,2])             #prints 0th row 2nd column element
print(a[:,2])
print()
print(a[0:2,:])          #prints o to 1 rows and all columns

a=np.linspace(1,10,5)    #divides 1-10 into 5 equal parts
print(a)

a=list(range(5))
print(a)

a=np.arange(0,25,5)       #divides 0 to 25 into increment of 5; 25 is excluded 
print(a)

a=np.arange(0,26,5)     #divides 0 to 25 into increment of 5; 26 is excluded
print(a)


[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
3
[ 3  5 10]

[[1 2 3 4]
 [3 4 5 6]]
[ 1.    3.25  5.5   7.75 10.  ]


In [60]:
#aggregate functions
a=np.array([(8,9),(10,11),(12,13)])
print(len(a))
print(a.min())
print(a.max())
print(a.sum())
print(a.sum()/a.size)
print(a.mean())

#math functions

import numpy as np
a=np.array([(1,0,3),(3,4,5)])
print(np.sqrt(a))
print(np.std(a))
print(np.log(a))
print()
b=np.sqrt(a)
print(b.round(2))

x=np.array([(1,2),(3,4)])
y=np.array([(5,6),(7,8)])
print(x)
print(y)
print(x+y)
print(x-y)
print()
print(x*y)      #performs multiplication on matrix elements like(1*5),(2*6), etc in this case
print(x/y)  
print(x%y)
print(x@y)      #performs proper matrix multiplication as done in maths
#print(np.dot(x,y))
#print(np.add(x,y))

3
8
13
63
10.5
10.5
[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]
1.699673171197595
[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]

[[1.   0.   1.73]
 [1.73 2.   2.24]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[19 22]
 [43 50]]


C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: divide by zero encountered in log
  app.launch_new_instance()


In [63]:
#help
#?np.array

#joining arrays
#d=np.concatenate((x,y),axis=0)
print(d)
print()

print(np.vstack((x,y)))
print(np.hstack((x,y)))

#convert array into a single row
print(x)
z=x.ravel()                      #converts 2D to 1D
print(z)
print(z.reshape(2,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [65]:
import numpy
?numpy.mean

In [27]:
#append function is used to join 2 arrays of unequal sizes
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(6,7),(9,10)])
new_array =np.append(x,y)
print(new_array)
new_array =np.reshape(new_array,(5,2))
print(new_array)
print()
#inserting elements in the array
#x=np.array([(1,2,3),(4,5,6)])
new_array=np.insert(x,[1,3,4],[5,10,15])
print(new_array)

#deleting elements from array
new_array=np.delete(new_array,[1,2])
print(new_array)

[ 1  2  3  4  5  6  6  7  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 9 10]]

[1 5 2 3 5 4 5 5 6]
[1 3 5 4 5 5 6]


In [58]:
#read a file from given location
read_file=np.genfromtxt(r'D:\prakruti\sample.txt',delimiter=",")#,unpack=False)
                        #, skip_header=1,delimiter=",",unpack=False)
print(read_file)


[[nan nan nan]
 [ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [12]:
import pandas as pd
import numpy as np
data=np.array([101,102,103,104])
s=pd.Series(data)
print(s)
print()

print(s[1])
s[1]=100
print(s)

s=pd.Series(data,index=[1001,1002,1003,1004])
print(s)
#print(s[1])                            #since index nos. are over written, thus there is no index no.1

list1=np.arange(1001,1005,1)
s=pd.Series(data,index=list1)
print(s)

s=pd.Series(data,index=["a","b","c","d"])
print(s)
print(s['b'])                            #since index nos. are over written, thus there is no index no.1

data={'a':0.,'b':1.,'c':2}
s=pd.Series(data)
print(s)

print(s['a'])
print()
print(s[-2:])

0    101
1    102
2    103
3    104
dtype: int32

102
0    101
1    100
2    103
3    104
dtype: int32
1001    101
1002    100
1003    103
1004    104
dtype: int32
1001    101
1002    100
1003    103
1004    104
dtype: int32
a    101
b    100
c    103
d    104
dtype: int32
100
a    0
b    1
c    2
dtype: int64
0

b    1
c    2
dtype: int64


# DATA FRAMES

In [41]:
data=[['Amit',40],['Nikita',23],['Clara',33]]
df=pd.DataFrame(data)
#df=pd.DataFrame(data, columns=["Name","Age"]) 
print(df)

df.columns=["Name","Age"]       #to assign column names after data set is imported.
print(df)

#indexed data frame from dict
data={'Name':['Amit','Nikita','Clara'],'Age':[40,23,33]}
df=pd.DataFrame(data)
print(df)

df=pd.DataFrame(data, index=['rank1','rank2','rank3'])
print(df)

df[["Name","Age"]]    #to define the headings and indexes

        0   1
0    Amit  40
1  Nikita  23
2   Clara  33
     Name  Age
0    Amit   40
1  Nikita   23
2   Clara   33
     Name  Age
0    Amit   40
1  Nikita   40
2   Clara   40
         Name  Age
rank1    Amit   40
rank2  Nikita   40
rank3   Clara   40


Name  Age
rank1    Amit   40
rank2  Nikita   40
rank3   Clara   40

In [39]:
#adding a column
df['address']=['Mumbai','Pune','Mumbai']
df

#re ordering the variables in a data frame
df=df[['Name','address','Age']]
#print(df)
df

df["NewCol"]=[5,10,12]
print(df)
df["Rev_Col"]=df["NewCol"]*2
print(df)

#dropping a variable or column
del df['NewCol']
print(df)

#df=df.drop('rank1')
df=df.drop('Rev_Col', axis=1)     #axis=1 = columns; axis=0 = rows  
print(df)



         Name address  Age  NewCol
rank1    Amit  Mumbai   40       5
rank2  Nikita    Pune   23      10
rank3   Clara  Mumbai   33      12
         Name address  Age  NewCol  Rev_Col
rank1    Amit  Mumbai   40       5       10
rank2  Nikita    Pune   23      10       20
rank3   Clara  Mumbai   33      12       24
         Name address  Age  Rev_Col
rank1    Amit  Mumbai   40       10
rank2  Nikita    Pune   23       20
rank3   Clara  Mumbai   33       24
         Name address  Age
rank1    Amit  Mumbai   40
rank2  Nikita    Pune   23
rank3   Clara  Mumbai   33


In [40]:
#accessing data elements using indexes and labels
#loc = row label, iloc= column label or index no.
#df.loc[inclusive:inclusive]
print(df.loc['rank2'])
print(df.loc['rank2':'rank3'])

#df.iloc[inclusive:exclusive]
print(df.iloc[0:1])

print(df.loc["rank2":"rank3",["address","age"]])
print(df.iloc[:,[1,2]])


Name       Nikita
address      Pune
Age            23
Name: rank2, dtype: object
         Name address  Age
rank2  Nikita    Pune   23
rank3   Clara  Mumbai   33
       Name address  Age
rank1  Amit  Mumbai   40
      address  age
rank2    Pune  NaN
rank3  Mumbai  NaN
      address  Age
rank1  Mumbai   40
rank2    Pune   23
rank3  Mumbai   33


In [36]:
#saving df to a file
df.to_csv(r'D:\Prakruti\temp.csv',index=True, header=True)   #.txt as well

df.to_excel('temp.xlsx', index=False, header=True)
print('Done')



Done


In [51]:
df.set_value('rank2',['Name','Age'],['Ramesh',40])  #set value -->point to a specific value and change the observation

df.loc[(df.Name=="Ramesh"),["Name"]]=["Rahul"]#or df.loc[(df.Name=="Ramesh")&(df.address=="Pune"),["address","Name"]]=["Bangalore","Rahul"]
df

df.sort_values(['Age','Name'],ascending=True)
print(df['Name'].unique())
df.sort_index(axis=1,ascending=True)

['Amit' 'Rahul' 'Clara']


C:\Users\Prakruti Joshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.


Age   Name
rank1   40   Amit
rank2   40  Rahul
rank3   40  Clara